### PR TITLE
feat: add card around the gaps chart

### PR DESCRIPTION
**Pull request by shootermv**
# Description
add a `card` layout around the chart area

## screenshots
image

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
lgtm

**Comment by NoamGaash** [comment]
why changing the sorting mode triggers data reloading?

**Comment by shootermv** [comment]
purpose of my change - is better styling (improving the look)
data reloading was before my change 
actually - the request is totally identical for both `by hour` and `by severity` modes:
````
rides_execution/list?limit=10000&date_from=2023-10-30&date_to=2023-11-05&operator_ref=4&line_ref=27383
rides_execution/list?limit=10000&date_from=2023-10-30&date_to=2023-11-05&operator_ref=4&line_ref=27383
```` 
may be it is something we need to get fixed at next PR

**Comment by NoamGaash** [comment]
@shootermv could you please create an issue for that? thanks :pray:

**Pull request merged**
