### PR TITLE
feat(line-profile): add a map

### LINKED ISSUE #542: Add a map to the line profile page
# Where is it?
1. go here:
image
2. go back in time :timer_clock: 
image
3. click a bus:
image
4. click the line title:
image

# The problem
It's an ugly, unfinished page

# What could you do?
Help us!
Add a map (it could be the same map from [here](https://open-bus-map-search.hasadna.org.il/single-line-map))

### PR DESCRIPTION
**Pull request by Tamir198**
Added a map to the bottom of this page: 

image

Fix #542

### CODE REVIEW

**Comment by Tamir198** [comment]
So do you want me to do it in a new pr?

**Comment by NoamGaash** [comment]
@Tamir198 it's up to you :)

**Comment by Tamir198** [comment]
I think I will want you to merge this and do it in a new pr just to prevent bug conflicts with [Darkmift](https://github.com/Darkmift) user who is also working on this part on the page.

Sounds good?

**Comment by NoamGaash** [comment]
@Tamir198 sure, thanks. Let's merge it.
I gave you permissions to the repo, so feel free to merge things whenever you want (as long as there are no regressions and anyone made at least one code-review)

**Comment by NoamGaash** [comment]
@all-contributors please add @Tamir198 for his code :clap: :medal_sports:

**Pull request merged**
