### PR TITLE
Moved colorIcon and change to busIcon

### LINKED ISSUE #40: Move `colorIcon` To a Separate File
The `colorIcon` function is defined in two files (`RealTimeMapPage` and `BusLayer`) and have the same functionality and style.
Do you want to keep it as is or to move it to a separate file?

### PR DESCRIPTION
**Pull request by guyStrauss**
# Description
* Change colorIcon to busIcon and moved to under utils/ 

close #40

### CODE REVIEW

**Review by rzarviv — APPROVED** [review]
Good Job @guyStrauss!

**Review by NoamGaash — APPROVED** [review]
perfect! :medal_sports:

**Comment by NoamGaash** [comment]
image

**Comment by NoamGaash** [comment]
great job! thank you :pray: :star:

**Comment by NoamGaash** [comment]
the linter can be ran locally by using the `yarn run lint` command :)

**Comment by guyStrauss** [comment]
> the linter can be ran locally by using the `yarn run lint` command :)

Yes I set my vs code to auto lint every save, I probably merge requested before fixing the issue

**Comment by NoamGaash** [comment]
the linting fail on the latest commit of this branch - so please make sure you pushed all of your changes,
thank you :pray:

**Comment by NoamGaash** [comment]
@guyStrauss this kind of warnings doesn't get automatically fixed
image

**Comment by guyStrauss** [comment]
Hey @NoamGaash 
Fixed the lint problems, and merged main into this current branch to make sure there are no conflits

**Pull request merged**
