### PR TITLE
chore: add eslint import order rule

### PR DESCRIPTION
**Pull request by ArkadiK94**
# Description
<Please describe the suggested changes>
why: to have order for the imports

how: add rule of eslint-plugin-import

## screenshots
<paste here>
none

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]

**Comment by NoamGaash** [comment]
Thank you!

**Comment by NoamGaash** [comment]
@ArkadiK94 feel free to merge

**Comment by NoamGaash** [comment]
@ArkadiK94 do you need any help?

**Comment by ArkadiK94** [comment]
@NoamGaash Sorry, I missed the notifications, I will handle the conflicts and merge.

**Comment by ArkadiK94** [comment]
@NoamGaash I handled the conflicts, however, there are three checks that was skipped, is it ok to merge?

**Comment by NoamGaash** [comment]
@ArkadiK94 sure, it's great.
We skip making a preview of your changes when you create them from a forked repository because of security concerns.
I made a PR yesterday that will allow doing it securely

**Pull request merged**
