### PR TITLE
Put the shell code in separate files

### PR DESCRIPTION
**Pull request by ArkadiK94**
# Description
<Please describe the suggested changes>
Related to pr #171 

Why: Make the code cleaner, and not reuse code
How: Put the shell code in separate file and use this code from file when needed

## screenshots
<paste here>
Don't need here

### CODE REVIEW

**Comment by NoamGaash** [comment]
https://github.com/marketplace/actions/clean-git-status
WDYT?

**Review by NoamGaash — APPROVED** [review]

**Comment by ArkadiK94** [comment]
Hmm, the repo of this github action has only 9 starts. It contains only few files and doesn't affect the production but still do you want to take the risk using it in this project? 🤔

**Comment by NoamGaash** [comment]
it doesn't seem so riskey
anyway, we can also write a composite action instead
https://docs.github.com/en/actions/creating-actions/creating-a-composite-action

**Comment by ArkadiK94** [comment]
Yup, I will do it. I have one question regarding it. Do you want me create the action folder inside this project or add new repo in the Hasadna github page so people could use it in future projects? This action can be helpful almost in every project.

**Comment by NoamGaash** [comment]
There are many github actions that are already available for this

**Comment by ArkadiK94** [comment]
@NoamGaash I created new github action https://github.com/ArkadiK94/action-git-clean-tree and used it here.

**Review by NoamGaash — APPROVED** [review]
looks great :clap:

**Pull request merged**
