### PR TITLE
fix: allow donate modal to dynamically change for devices 

### PR DESCRIPTION
**Pull request by yontank**
# Description
Dynamically changes DonationModal to support (hopefully) most devices, 
as written in #942 
## screenshots
S

### CODE REVIEW

**Comment by NoamGaash** [comment]
It looks great, thank you!
few tips - 

1. merge from main to get the latest version (with the right color)
2. I think the desktop version should not ne aligned to the center - what do you think?

**Comment by yontank** [comment]
yeah I agree, setting it to the left looks much better,

got 2 questions:  
1) Is it okay to use CSS styles right inside the JSX tags? for example  
2) about the jgive image, is it okay that it's moved to the left?

**Comment by NoamGaash** [comment]
1. it's ok, but it's better to use scss or styled components
2. sure :pray: 

by the way, I think that we should add some tests to see how things look in English (not just this modal)

**Review by NoamGaash — APPROVED** [review]
I think it's a great improvement - so please feel free to merge if you feel comfortable with that code, and open another PR if you want to make more progress :pray:

**Comment by yontank** [comment]
Hey, Sure thing! I thought about creating the tests and then merging, but it's probably gonna take some time since I'm new PlayWright  😢

**Pull request merged**
