### PR TITLE
Issue #72 Solve eslint warning

### PR DESCRIPTION
**Pull request by amrishtembe1998**
# Description
Please describe the suggested changes

1. Removed linting error
2. Set max warnings to 0 to fail the job if warnings are present

## screenshots
<-- paste here -->

### CODE REVIEW

**Comment by amrishtembe1998** [comment]
Hi @NoamGaash Could you please review the PR?

**Review by NoamGaash — APPROVED** [review]
looks great!
should we close the previous PR?

**Comment by amrishtembe1998** [comment]
> looks great! should we close the previous PR?



> looks great! should we close the previous PR?

Yes you can close the Previous PR

**Comment by amrishtembe1998** [comment]
Hi @NoamGaash Could you please merge this after on or after 1st October?

**Comment by NoamGaash** [comment]
I think it's ready to be merged,
why waiting?

**Comment by amrishtembe1998** [comment]
Hacktoberfest is starting from 1st october.. though this PR will count in that event if merged on or after 1st october.
If it's urgent you can merge.. no issue

**Comment by NoamGaash** [comment]
Sure, thanks!
:blush: :clap:

**Comment by NoamGaash** [comment]
Happy October!

**Pull request merged**
