### PR TITLE
fix: cancel request when input get clear

### LINKED ISSUE #268: [Bug] Cancel Fetch/Axios Requests
There is a problem when we send a request and than click on the clear button, it clears the data but because the request still in progress when it will finish the data will still display.

https://github.com/hasadna/open-bus-map-search/assets/76536506/e31f8cf7-0228-47c9-8475-029b44bf9d6f

### PR DESCRIPTION
**Pull request by eyalyehia**
Cancel Fetch/Axios Requests Bug

close #268

### CODE REVIEW

**Comment by eyalyehia** [comment]
the file of storybook (HbarChart.stories) if you can ignore it this is my mistake

**Comment by NoamGaash** [comment]
@eyalyehia [run `git checkout main filename`](https://stackoverflow.com/questions/215718/how-can-i-reset-or-revert-a-file-to-a-specific-revision)

**Review by NoamGaash — APPROVED** [review]
It looks great! Thanks

**Review by shootermv — APPROVED** [review]
excellent!

**Pull request merged**
