### PR TITLE
docs: create contribution.md file

### LINKED ISSUE #194: create CONTRIBUTION.md file
I believe it should include:

- Links to the video tutorials on my youtube channel https://www.youtube.com/watch?v=6H6jkJCVhgk&t=4s&pp=ygUKbm9hbSBnYWFzaA%3D%3D https://www.youtube.com/watch?v=jEWG7nYKk_0&t=137s https://www.youtube.com/watch?v=DWp4cwd97TI
- Explanation about linting and testing
- links to discord and slack
- anything else comes up on your mind

### PR DESCRIPTION
**Pull request by NoamGaash**
# Description
close #194

### CODE REVIEW

**Comment by amabelleS** [comment]
Maybe we should also include somthing like this: 
## How should I write my commits?
[link to the Git Commit Guidelines](https://ec.europa.eu/component-library/v1.15.0/eu/docs/conventions/git/#:~:text=chore%3A%20Changes%20to%20the%20build,libraries%20such%20as%20documentation%20generation)

I don't know how much it's relevant to #320 
It could be in another issue.

**Comment by shootermv** [comment]
@amabelleS you totally right -
`commit messages convention` it is something that should be in the contribution guide

**Comment by NoamGaash** [comment]
@amabelleS @shootermv  I won't do it in this PR.
If you don't approve this, let's close it and delete that branch.

**Review by shootermv — APPROVED** [review]

**Comment by shootermv** [comment]
@NoamGaash  of course, i didnt mean everything should be in the same Pr

**Pull request merged**
