### PR TITLE
test: add test for getting to research page with an easter egg

### PR DESCRIPTION
**Pull request by YaelChen**
# Description
After the page loads, type "geek" and get the research page.

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
That's really cool! But focusing on Easter eggs is less important - that's an internal feature so breaking it is less of a concern

**Comment by YaelChen** [comment]
> 
Sure, I was investigating a bit, as I wondered why there isn't data in the Actual rides section
image

And if there's more important stuff you think should be done, let me know :)

**Comment by NoamGaash** [comment]
there's a bug with the actual rides - I'm not sure where it's coming from, but seems like the actual rides miss some columns so it doesn't appear in the dashboard... I hope someone will solve it.
Regaring testing - I think there is little to no coverage of the bus tooltip and the youtube modals. Also, I think it could be nice to add visual assertions for regions - `eyes.check('step name', Target.region(page.getByRole(...)))`.
Also, other nice contribution would improving the backend mocking - it can be done by using `page.route` or HAR files. It's more complicated, but it will make our tests more stable and performant and that's important

**Comment by YaelChen** [comment]
@NoamGaash So, YouTube modals can't be tested with automation as bots are being blocked.
Can you provide details on the Bus Tooltips we want to test? What are bus tooltips?

**Comment by NoamGaash** [comment]
@YaelChen the modal itself can be tested - to see that it's opened, and that the iframe has the right `src` attribute (even if the video is not loaded at all). Also, the iframe should be visible. The only thing we should avoid is testing beyond the scope of our application - the functionality of you-tube can change and break but we should not consider that as a regression in our codebase.

Regarding the bus tooltip - it can be found in the storybook, and inside every map -
image

**Pull request merged**
