### PR TITLE
feat: add HBarChart variations to stories

### PR DESCRIPTION
**Pull request by R894**
# Summary
* Initializes i18n in .preview so that the hebrew text displays
* add LinesHBarChart story
* add OperatorHbarChart story

### CODE REVIEW

**Comment by NoamGaash** [comment]
Just sharing my thought - do we want our stories to fetch real data?
Maybe we should prefer using storybook for components like HBarChart rather then ArrivalByTimeChart, because storybook is an educational resource for new developers about how to use our components, and it's more likely that they will want to reuse generic components

**Comment by R894** [comment]
> Just sharing my thought - do we want our stories to fetch real data? Maybe we should prefer using storybook for components like HBarChart rather then ArrivalByTimeChart

I agree completely! 
How about adding the variations of HBarChart? otherwise we can just keep the i18n fix and rename the PR

**Review by NoamGaash — APPROVED** [review]
Thanks, that's great!

**Comment by NoamGaash** [comment]
@all-contributors please add @R894 for code and test

**Pull request merged**
