### PR TITLE
style: center map automatically when data changes

### LINKED ISSUE #726: center map automatically
On the single line map page and line profile page, the map could be automatically centered to the mean of all available data points whenever new data is loaded to the map

### PR DESCRIPTION
**Pull request by itsoriki**
# Description
Resolve #726 
- Center the map to the mean of all available data points whenever new data is loaded to the map
- Fix some typos in `CONTRIBUTING.md`
- Add `.prettierrc` file for a smooth prettier development experience

### CODE REVIEW

**Review by NoamGaash — CHANGES_REQUESTED** [review]
I'm not sure regarding the idea of introducing another component.
You can make a `meanPoint` function, and `useEffect` to execute the `map.setView` whenever this center changes. won't it be easier?

**Comment by itsoriki** [comment]
You're correct - the thing is this useEffect **needs to sit inside the map context** in order for the setView to work properly - For that we must use one of our own components, i.e. the `MapIndex` component or introduce a new one with a clear name and a single purpose being the centering mechanism.

What do you think @NoamGaash ?

**Comment by itsoriki** [comment]
Check out the error being thrown when I try to do as you suggest:
image

**Comment by NoamGaash** [comment]
I see. Have you tried editing `center={position.loc}`?

**Review by NoamGaash — APPROVED** [review]
I see that the `center` property is assumed to be immutable.
image

I think we should consider making a <MapContent> component that will be the child component of the `<MapContainer>`, and place all the content of this component in there. The current dummy-component implementation is very confusing and I believe we should try to avoid it. If it's too complicated you can merge it as-is, or you can make a second PR to refactor it later

**Pull request merged**
