### PR TITLE
feat: add map with buses in given minute

### PR DESCRIPTION
**Pull request by NoamGaash**
image

### CODE REVIEW

**Comment by NoamGaash** [comment]
@OriHoch I see our CI pipeline creates a docker image. is it deployed to a server?

**Comment by OriHoch** [comment]
yes https://open-bus-map-search.hasadna.org.il/dashboard

**Comment by NoamGaash** [comment]
so cool! thanks!

**Comment by NoamGaash** [comment]
@OriHoch does it take more than a hour?

**Comment by OriHoch** [comment]
no, there was a problem, it's deployed now

**Pull request merged**
