### PR TITLE
style: move element to the right

### PR DESCRIPTION
**Pull request by rivka14**
The sidebar toggle button's position align to the right side.

### CODE REVIEW

**Comment by NoamGaash** [comment]
Hi, thanks for submitting this pull request!
Did you check the layout when switching the language?
I believe `display: flex` could do a better job  here

**Comment by rivka14** [comment]
@NoamGaash  thanks for your feedback! I've made the following updates based on your suggestions:
- Ensured proper layout when switching languages.
- Updated to use `flexbox `.

Is everything good now?
Thank you so much for your help!

**Comment by NoamGaash** [comment]
@rivka14 perfect, thank you! :clap: :bus: 
would you please just remove the yarn.lock file?

**Review by NoamGaash — APPROVED** [review]
Thank you! :clap: :pray:

**Comment by NoamGaash** [comment]
Thank you @rivka14 !
@all-contributors please add @rivka14  to code :)

**Pull request merged**
