### PR TITLE
docs: Add instructions for running the project locally

### PR DESCRIPTION
**Pull request by UrielOfir**
This pull request adds detailed instructions on how to run the project locally. It includes steps to fork the repository, clone it to your local machine, navigate to the project directory, install dependencies, and run the project. These instructions will help new contributors get started with the project easily.

### CODE REVIEW

**Comment by shootermv** [comment]
We already have some kind of instructions of how-to-run-project at CONTRIBUTION.md file, 
Sure they can be improved
It can be better to look at this file and update it with improved version of instructions

**Comment by UrielOfir** [comment]
Ok, 
So there should be at least a link in the main README that points to instructions on how to run locally.
As far as I know it is common to write the instructions in the README so at least there should be a reference.

**Comment by NoamGaash** [comment]
That's great.
Can we merge those instruction to our contribution.md file somehow?
you're right about the link - it could be extreamly helpful for newcomers

**Comment by UrielOfir** [comment]
> That's great. Can we merge those instruction to our contribution.md file somehow? you're right about the link - it could be extreamly helpful for newcomers

@NoamGaash 
I will update the PR

**Comment by UrielOfir** [comment]
@NoamGaash 
Can you look at it now?
I moved the instructions to the contribution file.

**Review by shootermv — APPROVED** [review]

**Review by NoamGaash — APPROVED** [review]
it's perfect! thank you! :clap:

**Pull request merged**
