### PR TITLE
Fix conflict

### PR DESCRIPTION
**Pull request by ArkadiK94**
remove unused variables that shown because of git merge conflict

### CODE REVIEW

**Comment by ArkadiK94** [comment]
@NoamGaash I need to marge my last commit to 
- #61 

However, I don't find this branch. How can I merge only my last commit to this branch?

**Comment by NoamGaash** [comment]
@ArkadiK94 I'm not sure I understand your question - do you try to edit existing pull request (#61)?
I use GitHub CLI for such tasks
https://cli.github.com/manual/gh_pr_checkout

**Comment by ArkadiK94** [comment]
Yes, thanks, I will try it out.

**Comment by NoamGaash** [comment]
closing for now, please re-open if relevant :smiley:

**Pull request closed without merging**
