### PR TITLE
ci: fix base href

### PR DESCRIPTION
**Pull request by NoamGaash**
# Description
closing #329

### CODE REVIEW

**Comment by donno2048** [comment]
This change was introduced just to change the base URL?

I don't like the idea of doing ift in the CI/CD

**Comment by NoamGaash** [comment]
@donno2048 this url is only used within the ci pipeline, to generate the preview comment above

**Comment by donno2048** [comment]
I'm unfamiliar with the original problem, does it solve it?

And anyway why do you use a `should_run` job and not just `if env.should_run` in all the other jobs?

**Comment by NoamGaash** [comment]
Opps.
I see it's not working as expected
seems like the preview link still redirects to https://s3.amazonaws.com/dashboard

**Pull request closed without merging**
