### PR TITLE
refactor: replaced some Ant components with MUI components.

### PR DESCRIPTION
**Pull request by SariHop**
## Description
#158 

Started to replace Ant components with MUI components. There is more progress to be made, but I would like to get feedback on my initial work.

### CODE REVIEW

**Comment by NoamGaash** [comment]
Hi, thanks for your efforts!
Please consider configuring eslint in your ide, or run `npm run lint:fix` to fix lint errors

**Comment by SariHop** [comment]
I ran the command `npm run lint:fix`. 
This is my first PR, so I would like to know if there is anything else I should do or know
before I commit the changes.

**Comment by shootermv** [comment]
I think you should be more pesific about - which components you are about
to replace ("some" is too general). my opinion - it would be ev3n better to
replace only one component per step...

**Comment by NoamGaash** [comment]
Hi @SariHop , it's always good to commit any improvement. Right now, it's hard to check your pull request as it have many warnings on it. It is recommended to solve all lint errors before asking for a code review

**Comment by SariHop** [comment]
This is more information about my changes:
*  Bug report form:
Use CardContent and Card from MUI and change the uploud icon
*  About form :
Switch the Space(Ant) with Stack(MUI)
* Imported all typografy from MUI .
* Imported all  alert from MUI.
* Switched all Spin (Ant) with CircularProgress (MUI).

**Review by NoamGaash — APPROVED** [review]
Great job!
I did notice the size of your headers is a little different. Is it on purpose? Are we ok with it?

**Comment by shootermv** [comment]
one little problem i saw (not sure if it has something with the change...)
there are 2 dollar icons at the topbar
image

**Comment by shootermv** [comment]
Thanks! Not sure about PR, but I will open an issue.

**Comment by SariHop** [comment]
The differences between MUI and Ant's text header size are quite significant. I found this size to be the most suitable so that the title would be noticeable and readable.
@NoamGaash

**Comment by NoamGaash** [comment]
@SariHop Thanks!

**Pull request merged**
