### PR TITLE
fix gap sort by date

### PR DESCRIPTION
**Pull request by SergeyArenzon**
# Description
Solves [Bug] Sort Hours in Gaps Page #265
Fix for unsorted gaps with "נסיעה שלא תוכננה".
Now it should sort it with others gaps by its actual time.

before fix: unplanned rides unsorted with other rides
Screenshot 2023-12-02 at 20 11 12
after fix: unplanned rides sorted with other rides by its actual time.
Screenshot 2023-12-02 at 20 19 28

### CODE REVIEW

**Review by shootermv — CHANGES_REQUESTED** [review]
i think the `yarn.lock` file should not change (since no new packages installed at this PR)

**Comment by SergeyArenzon** [comment]
> i think the `yarn.lock` file should not change (since no new packages installed at this PR)

yarn.lock reverted back.

**Comment by NoamGaash** [comment]
@SergeyArenzon 
image
for next time - please be aware of this button :)

**Review by shootermv — APPROVED** [review]

**Comment by shootermv** [comment]
looks very good!
after merging the latest changes, i will be glad to merge the PR

**Pull request merged**
