### PR TITLE
test: public appeal page items

### PR DESCRIPTION
**Pull request by YaelChen**
# Description
I added a test to ensure the existence of all the "public appeal" headers.

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
Thank you! That's great.
After the English version will be translated, we'll be able to make a similar test for it as well :muscle:

**Comment by YaelChen** [comment]
Why isn't it translated yet btw? Is there a ticket for it?

בתאריך יום ב׳, 2 בדצמ׳ 2024, 17:01, מאת Noam Gaash ‏<
***@***.***>:

**Comment by NoamGaash** [comment]
there are some tickets regarding this page and/or translations, some of them are stale by now.
I'll close the irrelevant cards. I can't find any specific card for translating the public appear page, opening an issue would be a good idea

- https://github.com/hasadna/open-bus-map-search/issues/90
- https://github.com/hasadna/open-bus-map-search/issues/109
- https://github.com/hasadna/open-bus-map-search/issues/768

**Comment by YaelChen** [comment]
This test is failing, and I wonder what do I miss (choosing params in "קיום נסיעות" and organize by date/hour).
image

It seems that no operating companies are on the list, although there are when I do it manually, locally, or on the web.

**Comment by NoamGaash** [comment]
In the "publish test results" I found the link to the report (we should fix the link in the comments, it's broken and I'm sorry about it. I'm not sure if we have an opened github issue for that or not):

- https://s3.amazonaws.com/noam-gaash.co.il/12136639818/open-bus/cd467971fa8e09ac91e58ccf1cb0a73af450645b/test-results/index.html
- https://s3.amazonaws.com/noam-gaash.co.il/12136639818/open-bus/cd467971fa8e09ac91e58ccf1cb0a73af450645b/test-results/trace/index.html?trace=https://s3.amazonaws.com/noam-gaash.co.il/12136639818/open-bus/cd467971fa8e09ac91e58ccf1cb0a73af450645b/test-results/data/1084256e108a2cd02859c7f590ef8b7f6e51865d.zip

Seems like it can't see "דן" in the dropdown - it didn't really load any option
image
In the network tab we can see some requests are cancelled:
image
it's because the request include the current date, which is not recorded in the HAR (network) file:
image

There are two ways to solve it
1. use[ `page.clock.setFixedTime`](https://playwright.dev/docs/clock#:~:text=setFixedTime%3A%20Sets%20the%20fixed%20time%20for%20Date.now()%20and%20new%20Date().) to set a constant date for the application
2. use [urlComperator](https://github.com/NoamGaash/playwright-advanced-har?tab=readme-ov-file#examples) to declare that two urls with different dates are essentially the same and the response for `gtfs_agencies/list?date_from=2024-12-01` can be used to respond requests to `gtfs_agencies/list?date_from=2024-12-02`

I think both approaches are valid, and open for other ideas.
You can see [this line](https://github.com/hasadna/open-bus-map-search/blob/main/tests/realtimemap.spec.ts#L10C14-L10C24) as a reference for the second approach

**Pull request merged**
