### PR TITLE
feat: add stops list in the line profile page

### PR DESCRIPTION
**Pull request by Tami-Co**
I added code to display the list of stops for the line.
As a result, there were redundant code sections, so I removed them.

### CODE REVIEW

**Comment by NoamGaash** [comment]
Hi @Tami-Co , would you like any help with the lint command?

**Comment by Tami-Co** [comment]
> Hi @Tami-Co , would you like any help with the lint command?

@NoamGaash I would be happy to know how to solve the CI/CD issues that have arisen.
Thanks!

**Comment by NoamGaash** [comment]
regarding the lint - running the command `npm run lint:fix` should solve the problem (use git to commit the lint fixes this command will make)
regarding the title of the pull request - let's add a `feat: ` prefix so it will match conventional commits guidelines.
we have this document with more information if you find it interesting - 
https://github.com/hasadna/open-bus-map-search/blob/main/CONTRIBUTING.md#why-do-i-get-a-red-x-commit-status
let me know how can we improve so it will be more accessible

**Comment by Tami-Co** [comment]
All checks have passed.
I would appreciate it if you could review the code.

**Comment by NoamGaash** [comment]
Thank you!
I'm not sure I fully understand the feature you have implemented - I can see you have added a dropdown to select a bus stop, but what happen if a user selects one of the stops? Also, if possible, would you provide a screenshot?
I've tried using the preview link to see the dropdown in action (`/profile/2419581`) but seems like something in the preview is broken:
image

**Comment by Tami-Co** [comment]
Currently, as a first step, I have added the list of bus stops, as you mentioned here:
צילום מסך 2024-11-27 020335

 Therefore, at the moment, when a user selects a bus stop, nothing happens.
  Attached is a screenshot as requested:
  
image

**Review by NoamGaash — APPROVED** [review]
Thank you! I guess I had internet connectivity problem or something as I wasn't able to see it locally. By list I thought of some `UL` and `LI` tags, but your solution is great.

**Pull request merged**
