### PR TITLE
Issue #72 solve eslint warnings 

### PR DESCRIPTION
**Pull request by amrishtembe1998**
Removed unused state variables which were causing eslint warnings

#72 Solve eslint warnings (https://github.com/hasadna/open-bus-map-search/issues/72)

### CODE REVIEW

**Comment by rzarviv** [comment]
Hi @amrishtembe1998 , please add a description for this PR and a hashtag ('#') for the issue you'd like to solve.

**Comment by amrishtembe1998** [comment]
Hi @rzarviv Updated the PR description... please have a look

**Review by NoamGaash — APPROVED** [review]
great!
could you set all warnings as errors?
https://eslint.org/docs/latest/use/configure/rules
bonus - use `process.env.CI` to make it an error in the CI, and keep it as a warning in the local environment
it can be on the same PR, or in a different one

**Comment by NoamGaash** [comment]
solved on #78 
thanks!

**Pull request closed without merging**
