### PR TITLE
fix(mobile): close menu after navigation

### LINKED ISSUE #413: Closing the menu when a user clicks on it

### PR DESCRIPTION
**Pull request by Mordechai1323**
Close the menu when a user clicks on an item in it, by setting `setDrawerOpen` to `false` when clicked.

close #413

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
lgtm.
suggestion - maybe we should add some comment about the `drawer` thing being mobile only

**Review by shootermv — APPROVED** [review]
looks great!

**Comment by shootermv** [comment]
@Mordechai1323 do you need a help with solve the conflicts?

**Comment by NoamGaash** [comment]
Hi, how are you? do you need any help or have any question?

**Review by shootermv — APPROVED** [review]

**Comment by Mordechai1323** [comment]
thanks❤️

**Comment by NoamGaash** [comment]
run `npm i`, and push the updated package-lock

**Comment by NoamGaash** [comment]
have you seen the build output?
image

**Pull request merged**
