### PR TITLE
refactor: Line json details

### PR DESCRIPTION
**Pull request by Tamir198**
This is a fix for #543 now it looks like this instead of json: 

image

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
Thanks! That's a nice first step toward a better UX for this page

**Comment by NoamGaash** [comment]
Sorry for the tests, it's my fault - I didn't think about the fact forks won't have access to this API key. Let's skip the visual tests on forks for now. I'll change it to `pull_request_target` event later to make sure that the visual tests will be executed

**Comment by Tamir198** [comment]
Great so we can merge this pr? do you need any thing else? 

@NoamGaash

**Comment by NoamGaash** [comment]
Sure, I'll merge, thanks

**Pull request merged**
