### PR TITLE
test: add test for trip existence

### PR DESCRIPTION
**Pull request by YaelChen**
# Description
My first test, created by codegen,
Choosing params under "קיום נסיעות" and organize by date/hour.

### CODE REVIEW

**Comment by NoamGaash** [comment]
Thanks for the contribution! Truly appreciate it.
Please run `npm run lint:fix` as described [here](https://github.com/hasadna/open-bus-map-search/blob/main/CONTRIBUTING.md#why-do-i-get-a-red-x-commit-status)

**Review by NoamGaash — APPROVED** [review]
lgtm, can be merged once the commit statuses are fine

**Comment by YaelChen** [comment]
Thanks @NoamGaash, forgot about the lint. only installed it now.
do I need to run it and push again without the useless "expect" (that I first thought i'll leave for future use)?

**Comment by NoamGaash** [comment]
Exactly, thanks!
once the lint issues are solved, the test statuses should be green

**Comment by YaelChen** [comment]
It still fails,
something about a render component I don't know?

      22 |   let renderedComponent: RenderResult
      23 |   beforeEach(() => {
    > 24 |     renderedComponent = render(
         |                               ^
      25 |       <ArrivalByTimeChart data={testBusData} operatorId={testBusData[0].id} />,
      26 |     )
      27 |   })

it does mention I need to ask the APPLITOOLS_API_KEY, as it is not defined. don't know if it has something to do with it.

**Comment by NoamGaash** [comment]
Hi Yael, it's not you fault and I apology for the bad experience, I have probably misconfigured something with the visual tests - the error `Test timeout of 180000ms exceeded while running "afterEach" hook` indicate that we have some performance problems, it's not really test failures.
I pushed a commit (https://github.com/hasadna/open-bus-map-search/commit/121e6d53677136a22e9be0b4252c7e7df758df30) to ignore this error and remove the timeout, and I'll try again.

regarding the API key - it's just a warning - the visual tests are skipped by default when your API key is not configured on your machine. If you want to execute the visual tests I'll send you the API key but it's really not that important, I hope that the fix I pushed to main will solve this error

**Comment by NoamGaash** [comment]
Great job! Thanks you :clap: 
Feel free to merge

**Pull request merged**
