### PR TITLE
fix: The term 'APPLITOOLS_BATCH_ID=uuidgen npx' is not recognized as the name of a cmdlet, function, script file, or operable program.

### PR DESCRIPTION
**Pull request by aviv1620**
# Description
on windows `npm run test` make the error
```
The term 'APPLITOOLS_BATCH_ID=uuidgen npx' is not recognized as the name of a cmdlet, function, script file, or operable program.
```

if windows user want set environment variables it need do this:
```
$Env:APPLITOOLS_API_KEY = "uuidgen "
npm run test
```

### CODE REVIEW

**Comment by YuvalMasada** [comment]
@aviv1620 
It might be a bit cumbersome and maybe not the best practice, but if it's only for windows users then maybe just add to the scripts the following action:
"test:e2e:ui:win": "set APPLITOOLS_BATCH_ID=`uuidgen` && playwright test --ui".
The build server won't be affected from this change.

**Review by NoamGaash — CHANGES_REQUESTED** [review]
The right solution would be using cross-env

**Comment by aviv1620** [comment]
OK I add cross-env

**Comment by NoamGaash** [comment]
Thanks!

**Pull request closed without merging**
