### PR TITLE
feat: modify StoryBook secret easteregg design 

### PR DESCRIPTION
**Pull request by ArkadiK94**
# Description
<Please describe the suggested changes>

- add image in the letter (favicon image)

- change colors like the dashboard colors

- add in readme

## screenshots
<paste here>

https://github.com/hasadna/open-bus-map-search/assets/76536506/e1811e11-21b3-4d5d-9b43-3dc86f640fa1

@NoamGaash What do you think?

### CODE REVIEW

**Review by NoamGaash — COMMENTED** [review]
Regarding the design  - that’s cool!
Regarding the secret passphrase, in the furure we would like to add more secret eastereggs, so `openbus` is too generic

**Comment by ArkadiK94** [comment]
1. Timetable
2. Schedule
3. Route map
4. Bus stop
5. Fare details
6. Transit updates
7. Service alerts
8. Passenger guide
9. Travel advisory
10. Public transport

Do you like an option from here? Do you have other suggestions?

**Comment by NoamGaash** [comment]
Why not keeping it as storybook?

**Comment by ArkadiK94** [comment]
Hmm, In my opinion,  this is not related to the topic of the site. However,  we can keep it 'storybook'.

**Comment by ArkadiK94** [comment]
I will leave it storybook for now :)

**Comment by NoamGaash** [comment]
thanks!

**Review by NoamGaash — APPROVED** [review]

**Pull request merged**
