### PR TITLE
fix: new agencies should appear in the dashboard

### LINKED ISSUE #789: new agencies should appear in the dashboard
we should call https://open-bus-stride-api.hasadna.org.il/gtfs_agencies/list?date_from=2024-06-01 with dynamic date argument to make sure new agencies appear

### PR DESCRIPTION
**Pull request by asidelnik**
Get agency list - added date_from yesterday.
Resolves #789

### CODE REVIEW

**Comment by asidelnik** [comment]
Code coverage was failing before I updated agencyList.ts.
npm run test:unit shows an error in: ArrivalByTimeChart.test.tsx

**Review by NoamGaash — APPROVED** [review]
Perfect!

**Comment by NoamGaash** [comment]
seems like the falling test can be related to a backend change
https://github.com/hasadna/open-bus-stride-api/issues/26

**Comment by NoamGaash** [comment]
@all-contributors please add @asidelnik to code

**Pull request merged**
