### PR TITLE
component/widget

### PR DESCRIPTION
**Pull request by yardenmezi**

### CODE REVIEW

**Review by shootermv — APPROVED** [review]

**Review by shootermv — CHANGES_REQUESTED** [review]
can i ask you to create storybook test too?

**Comment by NoamGaash** [comment]
Hi, I dont fully understand- seems like you've added a component nut didn't use it

**Comment by yardenmezi** [comment]
Fixed and done :)

**Review by NoamGaash — APPROVED** [review]

**Comment by NoamGaash** [comment]
the code looks great :+1:

**Review by shootermv — APPROVED** [review]
well done!

**Pull request merged**
