### PR TITLE
ci: refactor workflows

### PR DESCRIPTION
**Pull request by donno2048**
# Description

Mainly small changes and a whole re-write to `validate.yaml`

### CODE REVIEW

**Review by NoamGaash — APPROVED** [review]
Cool! It looks great. Thanks

**Comment by donno2048** [comment]
@NoamGaash Can you merge? Auto-merging is blocked because I removed two required tests

**Comment by NoamGaash** [comment]
Oh, right! Missed that. I'll make `validate/local-tests` required instead of `lint` and `test-unit`, as it contains both

**Comment by donno2048** [comment]
> Oh, right! Missed that. I'll make `validate/local-tests` required instead of `lint` and `test-unit`, as it contains both

I think you should just make `all-passed` required instead of `test`, `build` and `local-tests`

**Pull request merged**
